  en: {
    WELCOME:        `👋 Vho-tanganedzwa kha *KasiCommerce* — Muthusi wa bindu lavho!\n\nKha vha nange luambo:\n1️⃣ English\n2️⃣ isiZulu\n3️⃣ isiXhosa\n4️⃣ Sesotho\n5️⃣ Afrikaans\n6️⃣ Tshivenḓa`,
    AWAIT_NAME:     `Dzina lavho ndi nnyi?`,
    AWAIT_BIZ_NAME: `Dzina la bindu lavho?`,
    AWAIT_BIZ_TYPE: `Khethekanyo ya bindu lavho?\n\n1️⃣ Tshipaza / Vhengele\n2️⃣ Mavhudzi na Lunaka\n3️⃣ Zwiliwa\n4️⃣ Zwiambaro\n5️⃣ Tshumelo\n6️⃣ Zwinwe`,
    MAIN_MENU:      `🏠 *Main Menu*\n\n1️⃣ 📒 KasiBooks — Log income or expense\n2️⃣ 📊 KasiComply — Tax & compliance\n3️⃣ 🛒 KasiStore — My online store\n4️⃣ 💰 KasiCredit — Apply for a loan\n5️⃣ 📈 Reports — View my summary\n\nReply with a number.`,
    LOG_TYPE:       `Vha khou toda u rekhoda mini?\n\n1️⃣ 💚 Income (money in)\n2️⃣ 🔴 Expense (money out)\n3️⃣ 🏠 Main Menu`,
    LOG_AMOUNT:     `Mutengo? (e.g. 150)`,
    LOG_DESC:       `Ndi ya mini? (e.g. "Ndo rengisa khuhu tharu(3)")`,
    LOG_SAVED:      `✅ Yo rekhodiwa!\n\n1️⃣ Capture Income\n2️⃣ Capture Expense\n3️⃣ Main Menu`,
    LOG_CANCEL:     `Cancelled.\n\n1️⃣ Capture Income\n2️⃣ Capture Expense\n3️⃣ Main Menu`,
    COMPLY_MENU:    `📊 *KasiComply — Tax & Compliance*\n\n1️⃣ Check if I qualify for Turnover Tax\n2️⃣ Calculate my tax liability\n3️⃣ View my compliance calendar\n4️⃣ PAYE & employee costs\n5️⃣ My upcoming deadlines\n\nType *MENU* to go back.`,
    TT_Q1:          `📋 *Turnover Tax Qualifier*\n\nQuestion 1 of 3:\n\nWhat is your estimated *annual turnover* (total sales per year)?\n\nReply with the amount in Rands. (e.g. 450000)`,
    TT_Q2:          `Question 2 of 3:\n\nDo you own or run *more than one business*?\n\n1️⃣ No — just this one\n2️⃣ Yes — I have other businesses`,
    TT_Q3:          `Question 3 of 3:\n\nIs your business a *public company*?\n\n1️⃣ No — it's a small private business\n2️⃣ Yes — it's a public company`,
    TT_QUALIFIES:   `✅ *Great news! You qualify for Turnover Tax.*\n\nTurnover Tax replaces 3 separate taxes with one simple annual payment.\n\nYour estimated tax: *{amount}*\nDue once a year on 28 February.\n\n1️⃣ How do I register?\n2️⃣ Calculate my exact amount\n3️⃣ Back to menu`,
    TT_NOT_QUALIFY: `ℹ️ You do not qualify for Turnover Tax.\n\nReason: {reason}\n\n1️⃣ Learn about standard tax\n2️⃣ Back to menu`,
    TT_HOW_REGISTER:`📝 *How to Register for Turnover Tax*\n\n1. Go to sars.gov.za or SARS MobiApp\n2. Log in to eFiling\n3. Select "Register for Turnover Tax"\n4. Complete the TT01 form\n\n✅ Registration is free.\n\nType *MENU* to go back.`,
    CALC_Q1:        `💰 *Tax Calculator*\n\nWhat was your *total income* this month?\n\n(e.g. 12500)`,
    CALC_Q2:        `What were your *total expenses* this month?\n\n(e.g. 4200)\nReply 0 if none.`,
    CALC_RESULT:    `📊 *Your Tax Summary*\n\n💚 Income:   R{income}\n🔴 Expenses: R{expenses}\n📈 Profit:   R{profit}\n\n*Estimated Tax*\n{tax_detail}\n\nType *MENU* to go back.`,
    PAYE_Q1:        `👥 *PAYE Calculator*\n\nHow many employees do you have?`,
    PAYE_Q2:        `What is the total *monthly payroll* (all salaries combined)?\n\n(e.g. 8500)`,
    PAYE_RESULT:    `💼 *Employee Cost Breakdown*\n\n*Gross Salary:* R{gross}\n• PAYE: R{paye}\n• UIF (employee): R{uif_ee}\n\n*Net Pay: R{net}*\n\n*Your costs to SARS:*\n• UIF (employer): R{uif_er}\n• SDL: R{sdl}\n\n*Total Cost to You: R{total}*\n\nDue by 7th of each month.\n\nType *MENU* to go back.`,
    COMPLY_MENU:    `📊 *KasiComply*\n\n1️⃣ Turnover Tax check\n2️⃣ Tax calculator\n3️⃣ Compliance calendar\n4️⃣ PAYE calculator\n5️⃣ Key deadlines\n\nType *MENU* to go back.`,
    UNKNOWN:        `A thi pfesesi pdindulo yavho. Kha vha nwale *MENU* vh whone .`,
  },
}

  // ─── TSHIVENDA ──────────────────────────────────────────────────────────────
  ve: {
    WELCOME:        `👋 Ndaa! Ni a wanifhwa kha *KasiCommerce*!\n\nDzudzanyani luambo lwanu:\n1️⃣ English\n2️⃣ isiZulu\n3️⃣ isiXhosa\n4️⃣ Sesotho\n5️⃣ Afrikaans\n6️⃣ Tshivenḓa`,
    AWAIT_NAME:     `Dzina lanu ndi nnyi?`,
    AWAIT_BIZ_NAME: `Dzina la bizhineси lanu ndi nnyi?`,
    AWAIT_BIZ_TYPE: `Ni na mukhethwa munye wa bizhineси?\n\n1️⃣ Spaza / Shopo\n2️⃣ Mavhudzi & Vuhle\n3️⃣ Zwiliwa & Vhubiwa\n4️⃣ Zwiambaro\n5️⃣ Tshumelo\n6️⃣ Zwinwe`,
    MAIN_MENU:      `🏠 *Menyu ya Ndingo*\n\n1️⃣ 📒 KasiBooks — Rekhoda tshelede\n2️⃣ 📊 KasiComply — Mutakalo\n3️⃣ 🛒 KasiStore — Shopo yanga\n4️⃣ 💰 KasiCredit — Humbela ndevhe\n5️⃣ 📈 Ripoti\n\nFhindula nga nomboro.`,
    LOG_TYPE:       `Ni funa u rekhoda mini?\n\n1️⃣ 💚 Tshelede i tsena\n2️⃣ 🔴 Tshelede i bva\n3️⃣ 🏠 Menyu ya Ndingo`,
    LOG_AMOUNT:     `Ndi ya vhugai? (muthu 150)`,
    LOG_DESC:       `Yo vha ya mini? (muthu "ndo rengisa inkukhu tharu")`,
    LOG_SAVED:      `✅ Yo vhuludzwa!\n\n1️⃣ Rekhoda tshelede i tsena\n2️⃣ Rekhoda tshelede i bvaho\n3️⃣ Menyu ya Ndingo`,
    LOG_CANCEL:     `Yo khansela.\n\n1️⃣ Rekhoda tshelede i tsena\n2️⃣ Rekhoda tshelede i bvaho\n3️⃣ Menyu ya Ndingo`,
    COMPLY_MENU:    `📊 *KasiComply — Mutakalo*\n\n1️⃣ Tarisa Turnover Tax\n2️⃣ Vhala mutakalo wanga\n3️⃣ Sheduulu ya u tevhela\n4️⃣ PAYE na tshelede\n5️⃣ Datumu dza ndeme\n\nDzwala *MENU* u bva.`,
    TT_Q1:          `📋 Mbudziso 1 ya 3:\n\nTshelede yanu ya ṅwaha ndi ya vhugai?\n\n(muthu 450000 nga R450,000)`,
    TT_Q2:          `Mbudziso 2 ya 3:\n\nNi na bizhineси dze ḓi fhamba?\n\n1️⃣ Hai — iyi fhedzi\n2️⃣ Ee — ndi na dze ḓi fhamba`,
    TT_Q3:          `Mbudziso 3 ya 3:\n\nBizhineси yanu ndi khamphani ya lushaka?\n\n1️⃣ Hai — ya poraifhete\n2️⃣ Ee`,
    TT_QUALIFIES:   `✅ *Mafhungo a naka! Ni kona u wana Turnover Tax.*\n\nMutakalo wanu: *{amount}*\nU lefulwa nga la 28 February.\n\n1️⃣ Ndi ḓivhadzise hani?\n2️⃣ Vhala nambara ya ndaulo\n3️⃣ Vhuyelela kha menyu`,
    TT_NOT_QUALIFY: `ℹ️ A ni koni u wana Turnover Tax.\n\nMbuno: {reason}\n\n1️⃣ Ḓifhedzisa nga mutakalo wa ṱhukhu\n2️⃣ Vhuyelela kha menyu`,
    TT_HOW_REGISTER:`📝 *U Ḓivhadzisa Turnover Tax*\n\n1. Ya kha sars.gov.za\n2. Tsena kha eFiling\n3. Khetha "Register for Turnover Tax"\n4. Tisa foromu ya TT01\n\n✅ U ḓivhadzisa ndi mahala.\n\nDzwala *MENU* u bva.`,
    CALC_Q1:        `💰 Tshelede yanu ya mwedzi ndi ya vhugai?\n\n(muthu 12500)`,
    CALC_Q2:        `Tshelede dzine na shumisa ndi dza vhugai?\n\n(muthu 4200)\nDzwala 0 arali hu sina.`,
    CALC_RESULT:    `📊 *Mutsirelo wa Mutakalo*\n\n💚 Tshelede: R{income}\n🔴 Tshelede dza u shumisa: R{expenses}\n📈 Pfumo: R{profit}\n\n*Mutakalo wa u Lingedza*\n{tax_detail}\n\nDzwala *MENU* u bva.`,
    PAYE_Q1:        `👥 Ni na vhashumeli vha vhugai?`,
    PAYE_Q2:        `Mukovhe wa mwedzi wa vhashumeli vhothe ndi wa vhugai?\n\n(muthu 8500)`,
    PAYE_RESULT:    `💼 *Tshelede dza Vhashumeli*\n\n*Mukovhe:* R{gross}\n• PAYE: R{paye}\n• UIF: R{uif_ee}\n\n*Mukovhe wa u Hlambulula: R{net}*\n\n*Tshelede dzanu kha SARS:*\n• UIF: R{uif_er}\n• SDL: R{sdl}\n\n*Tshelede Yothe: R{total}*\n\nDzwala *MENU* u bva.`,
    UNKNOWN:        `A ndo pfesesa. Dzwala *MENU* u vhona zwikhethe zwanu.`,
  },
}